/**
 * ECDAT Audit Logging Subsystem — Phase 18.1 Event Types & Categories
 *
 * Defines the 11 required enterprise operational audit categories:
 * - login
 * - logout
 * - permission changes
 * - scans
 * - configuration changes
 * - policy changes
 * - remediation approval
 * - remediation execution
 * - export
 * - integration changes
 * - secret/credential operations
 */

const AUDIT_CATEGORIES = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PERMISSION_CHANGE: "PERMISSION_CHANGE",
  SCAN: "SCAN",
  CONFIG_CHANGE: "CONFIG_CHANGE",
  CONFIGURATION_CHANGE: "CONFIG_CHANGE",
  POLICY_CHANGE: "POLICY_CHANGE",
  REMEDIATION_APPROVAL: "REMEDIATION_APPROVAL",
  REMEDIATION_EXECUTION: "REMEDIATION_EXECUTION",
  EXPORT: "EXPORT",
  INTEGRATION_CHANGE: "INTEGRATION_CHANGE",
  SECRET_OPERATION: "SECRET_OPERATION",
});

const AUDIT_ACTIONS = Object.freeze({
  // 1. Login
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
  AUTH_LOGIN_LOCKED: "AUTH_LOGIN_LOCKED",
  AUTH_MFA_SUCCESS: "AUTH_MFA_SUCCESS",
  AUTH_MFA_FAILURE: "AUTH_MFA_FAILURE",

  // 2. Logout
  AUTH_LOGOUT: "AUTH_LOGOUT",
  LOGOUT: "AUTH_LOGOUT",
  AUTH_LOGOUT_ALL: "AUTH_LOGOUT_ALL",
  AUTH_TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",

  // 3. Permission Changes
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_ASSIGN: "ROLE_ASSIGNED",
  ROLE_REVOKED: "ROLE_REVOKED",
  ROLE_REVOKE: "ROLE_REVOKED",
  PERMISSION_GRANTED: "PERMISSION_GRANTED",
  PERM_GRANT: "PERMISSION_GRANTED",
  PERMISSION_REVOKED: "PERMISSION_REVOKED",

  // 4. Scans
  SCAN_TRIGGERED: "SCAN_TRIGGERED",
  SCAN_INGESTED: "SCAN_INGESTED",
  SCAN_COMPLETED: "SCAN_COMPLETED",
  SCAN_COMPLETE: "SCAN_COMPLETED",
  SCAN_FAILED: "SCAN_FAILED",
  SCAN_DELETED: "SCAN_DELETED",
  ALL_SCANS_CLEARED: "ALL_SCANS_CLEARED",

  // 5. Configuration Changes
  CONFIG_UPDATED: "CONFIG_UPDATED",
  CONFIG_UPDATE: "CONFIG_UPDATED",
  RETENTION_POLICY_CHANGED: "RETENTION_POLICY_CHANGED",
  RATE_LIMIT_CHANGED: "RATE_LIMIT_CHANGED",
  SECURITY_CONFIG_MODIFIED: "SECURITY_CONFIG_MODIFIED",

  // 6. Policy Changes
  POLICY_CREATED: "POLICY_CREATED",
  POLICY_UPDATED: "POLICY_UPDATED",
  POLICY_ACTIVATED: "POLICY_ACTIVATED",
  POLICY_ACTIVATE: "POLICY_ACTIVATED",
  POLICY_OVERRIDDEN: "POLICY_OVERRIDDEN",
  POLICY_ROLLED_BACK: "POLICY_ROLLED_BACK",
  POLICY_ROLLBACK: "POLICY_ROLLED_BACK",
  POLICY_CHANGE: "POLICY_UPDATED",

  // 7. Remediation Approval
  REMEDIATION_PLAN_APPROVED: "REMEDIATION_PLAN_APPROVED",
  REMEDIATION_APPROVE: "REMEDIATION_PLAN_APPROVED",
  REMEDIATION_PLAN_REJECTED: "REMEDIATION_PLAN_REJECTED",
  REMEDIATION_DUAL_CONTROL_SIGN: "REMEDIATION_DUAL_CONTROL_SIGN",

  // 8. Remediation Execution
  REMEDIATION_APPLIED: "REMEDIATION_APPLIED",
  REMEDIATION_APPLY: "REMEDIATION_APPLIED",
  PATCH_GENERATED: "PATCH_GENERATED",
  REMEDIATION_ROLLED_BACK: "REMEDIATION_ROLLED_BACK",
  REMEDIATION_FAILED: "REMEDIATION_FAILED",

  // 9. Export
  CBOM_EXPORTED: "CBOM_EXPORTED",
  EXPORT_CBOM: "CBOM_EXPORTED",
  SARIF_EXPORTED: "SARIF_EXPORTED",
  COMPLIANCE_BUNDLE_EXPORTED: "COMPLIANCE_BUNDLE_EXPORTED",
  REPORT_HTML_EXPORTED: "REPORT_HTML_EXPORTED",
  EXPORT_REPORT: "REPORT_HTML_EXPORTED",
  AUDIT_LOG_EXPORTED: "AUDIT_LOG_EXPORTED",

  // 10. Integration Changes
  KMS_INTEGRATION_CONFIGURED: "KMS_INTEGRATION_CONFIGURED",
  INTEGRATION_ADD: "KMS_INTEGRATION_CONFIGURED",
  TICKETING_INTEGRATION_CONFIGURED: "TICKETING_INTEGRATION_CONFIGURED",
  CI_INTEGRATION_CONFIGURED: "CI_INTEGRATION_CONFIGURED",
  INTEGRATION_REMOVED: "INTEGRATION_REMOVED",

  // 11. Secret/Credential Operations
  SECRET_ROTATED: "SECRET_ROTATED",
  SECRET_ROTATE: "SECRET_ROTATED",
  API_KEY_CREATED: "API_KEY_CREATED",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  CERTIFICATE_IMPORTED: "CERTIFICATE_IMPORTED",
  CERTIFICATE_ROTATED: "CERTIFICATE_ROTATED",
});

const AUDIT_STATUSES = Object.freeze({
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  DENIED: "DENIED",
  LOCKED: "LOCKED",
  ERROR: "ERROR",
});

/**
 * Maps each action to its canonical audit category.
 */
const ACTION_TO_CATEGORY_MAP = Object.freeze({
  [AUDIT_ACTIONS.AUTH_LOGIN_SUCCESS]: AUDIT_CATEGORIES.LOGIN,
  [AUDIT_ACTIONS.AUTH_LOGIN_FAILURE]: AUDIT_CATEGORIES.LOGIN,
  [AUDIT_ACTIONS.AUTH_LOGIN_LOCKED]: AUDIT_CATEGORIES.LOGIN,
  [AUDIT_ACTIONS.AUTH_MFA_SUCCESS]: AUDIT_CATEGORIES.LOGIN,
  [AUDIT_ACTIONS.AUTH_MFA_FAILURE]: AUDIT_CATEGORIES.LOGIN,

  [AUDIT_ACTIONS.AUTH_LOGOUT]: AUDIT_CATEGORIES.LOGOUT,
  [AUDIT_ACTIONS.AUTH_LOGOUT_ALL]: AUDIT_CATEGORIES.LOGOUT,
  [AUDIT_ACTIONS.AUTH_TOKEN_REVOKED]: AUDIT_CATEGORIES.LOGOUT,

  [AUDIT_ACTIONS.ROLE_ASSIGNED]: AUDIT_CATEGORIES.PERMISSION_CHANGE,
  [AUDIT_ACTIONS.ROLE_REVOKED]: AUDIT_CATEGORIES.PERMISSION_CHANGE,
  [AUDIT_ACTIONS.PERMISSION_GRANTED]: AUDIT_CATEGORIES.PERMISSION_CHANGE,
  [AUDIT_ACTIONS.PERMISSION_REVOKED]: AUDIT_CATEGORIES.PERMISSION_CHANGE,

  [AUDIT_ACTIONS.SCAN_TRIGGERED]: AUDIT_CATEGORIES.SCAN,
  [AUDIT_ACTIONS.SCAN_INGESTED]: AUDIT_CATEGORIES.SCAN,
  [AUDIT_ACTIONS.SCAN_COMPLETED]: AUDIT_CATEGORIES.SCAN,
  [AUDIT_ACTIONS.SCAN_FAILED]: AUDIT_CATEGORIES.SCAN,
  [AUDIT_ACTIONS.SCAN_DELETED]: AUDIT_CATEGORIES.SCAN,
  [AUDIT_ACTIONS.ALL_SCANS_CLEARED]: AUDIT_CATEGORIES.SCAN,

  [AUDIT_ACTIONS.CONFIG_UPDATED]: AUDIT_CATEGORIES.CONFIG_CHANGE,
  [AUDIT_ACTIONS.RETENTION_POLICY_CHANGED]: AUDIT_CATEGORIES.CONFIG_CHANGE,
  [AUDIT_ACTIONS.RATE_LIMIT_CHANGED]: AUDIT_CATEGORIES.CONFIG_CHANGE,
  [AUDIT_ACTIONS.SECURITY_CONFIG_MODIFIED]: AUDIT_CATEGORIES.CONFIG_CHANGE,

  [AUDIT_ACTIONS.POLICY_CREATED]: AUDIT_CATEGORIES.POLICY_CHANGE,
  [AUDIT_ACTIONS.POLICY_UPDATED]: AUDIT_CATEGORIES.POLICY_CHANGE,
  [AUDIT_ACTIONS.POLICY_ACTIVATED]: AUDIT_CATEGORIES.POLICY_CHANGE,
  [AUDIT_ACTIONS.POLICY_OVERRIDDEN]: AUDIT_CATEGORIES.POLICY_CHANGE,
  [AUDIT_ACTIONS.POLICY_ROLLED_BACK]: AUDIT_CATEGORIES.POLICY_CHANGE,

  [AUDIT_ACTIONS.REMEDIATION_PLAN_APPROVED]: AUDIT_CATEGORIES.REMEDIATION_APPROVAL,
  [AUDIT_ACTIONS.REMEDIATION_PLAN_REJECTED]: AUDIT_CATEGORIES.REMEDIATION_APPROVAL,
  [AUDIT_ACTIONS.REMEDIATION_DUAL_CONTROL_SIGN]: AUDIT_CATEGORIES.REMEDIATION_APPROVAL,

  [AUDIT_ACTIONS.REMEDIATION_APPLIED]: AUDIT_CATEGORIES.REMEDIATION_EXECUTION,
  [AUDIT_ACTIONS.PATCH_GENERATED]: AUDIT_CATEGORIES.REMEDIATION_EXECUTION,
  [AUDIT_ACTIONS.REMEDIATION_ROLLED_BACK]: AUDIT_CATEGORIES.REMEDIATION_EXECUTION,
  [AUDIT_ACTIONS.REMEDIATION_FAILED]: AUDIT_CATEGORIES.REMEDIATION_EXECUTION,

  [AUDIT_ACTIONS.CBOM_EXPORTED]: AUDIT_CATEGORIES.EXPORT,
  [AUDIT_ACTIONS.SARIF_EXPORTED]: AUDIT_CATEGORIES.EXPORT,
  [AUDIT_ACTIONS.COMPLIANCE_BUNDLE_EXPORTED]: AUDIT_CATEGORIES.EXPORT,
  [AUDIT_ACTIONS.REPORT_HTML_EXPORTED]: AUDIT_CATEGORIES.EXPORT,
  [AUDIT_ACTIONS.AUDIT_LOG_EXPORTED]: AUDIT_CATEGORIES.EXPORT,

  [AUDIT_ACTIONS.KMS_INTEGRATION_CONFIGURED]: AUDIT_CATEGORIES.INTEGRATION_CHANGE,
  [AUDIT_ACTIONS.TICKETING_INTEGRATION_CONFIGURED]: AUDIT_CATEGORIES.INTEGRATION_CHANGE,
  [AUDIT_ACTIONS.CI_INTEGRATION_CONFIGURED]: AUDIT_CATEGORIES.INTEGRATION_CHANGE,
  [AUDIT_ACTIONS.INTEGRATION_REMOVED]: AUDIT_CATEGORIES.INTEGRATION_CHANGE,

  [AUDIT_ACTIONS.SECRET_ROTATED]: AUDIT_CATEGORIES.SECRET_OPERATION,
  [AUDIT_ACTIONS.API_KEY_CREATED]: AUDIT_CATEGORIES.SECRET_OPERATION,
  [AUDIT_ACTIONS.API_KEY_REVOKED]: AUDIT_CATEGORIES.SECRET_OPERATION,
  [AUDIT_ACTIONS.CERTIFICATE_IMPORTED]: AUDIT_CATEGORIES.SECRET_OPERATION,
  [AUDIT_ACTIONS.CERTIFICATE_ROTATED]: AUDIT_CATEGORIES.SECRET_OPERATION,
});

module.exports = {
  AUDIT_CATEGORIES,
  AUDIT_ACTIONS,
  AUDIT_STATUSES,
  ACTION_TO_CATEGORY_MAP,
};
