const fs = require('fs');
const path = require('path');

const walkSync = function(dir, filelist) {
  const files = fs.readdirSync(dir);
  filelist = filelist || [];
  files.forEach(function(file) {
    if (fs.statSync(path.join(dir, file)).isDirectory()) {
      filelist = walkSync(path.join(dir, file), filelist);
    }
    else {
      if (file.endsWith('.tsx') || file.endsWith('.ts')) {
        filelist.push(path.join(dir, file));
      }
    }
  });
  return filelist;
};

const mapRegex = [
  // SVG Fills
  [/fill-slate-100/g, 'fill-text-primary'],
  [/fill-slate-300/g, 'fill-text-secondary'],
  [/fill-slate-400/g, 'fill-text-muted'],
  [/fill-rose-400/g, 'fill-critical'],
  [/fill-amber-400/g, 'fill-high'],

  // SVG Strokes
  [/stroke-slate-100/g, 'stroke-text-primary'],
  [/stroke-slate-300/g, 'stroke-text-secondary'],
  [/stroke-slate-400/g, 'stroke-text-muted'],

  // Gradients removal/simplification
  [/bg-gradient-to-[a-z]+/g, ''],
  [/from-slate-[0-9]+/g, ''],
  [/via-slate-[0-9]+(\/[0-9]+)?/g, ''],
  [/to-slate-[0-9]+/g, ''],
  
  [/from-cyan-[0-9]+/g, 'bg-brand'],
  [/to-indigo-[0-9]+/g, ''],
  [/hover:from-cyan-[0-9]+/g, 'hover:bg-brand-light'],
  [/hover:to-indigo-[0-9]+/g, ''],
  
  [/from-amber-[0-9]+(\/[0-9]+)?/g, 'bg-surface-2'],
  [/via-cyan-[0-9]+(\/[0-9]+)?/g, ''],
  [/to-indigo-[0-9]+(\/[0-9]+)?/g, ''],

  [/from-purple-[0-9]+/g, 'bg-surface-2'],
  [/from-indigo-[0-9]+/g, 'bg-surface-2'],

  // Shadows
  [/shadow-cyan-[0-9]+\/[0-9]+/g, ''],
  [/shadow-emerald-[0-9]+\/[0-9]+/g, ''],
  [/shadow-amber-[0-9]+\/[0-9]+/g, ''],
  
  // Specific Border edges
  [/border-l-rose-[0-9]+/g, 'border-l-critical'],
  [/border-l-amber-[0-9]+/g, 'border-l-high'],
  [/border-l-emerald-[0-9]+/g, 'border-l-success'],
  [/border-l-slate-[0-9]+/g, 'border-l-border'],
  [/border-l-cyan-[0-9]+/g, 'border-l-pqc'],
  [/border-l-blue-[0-9]+/g, 'border-l-brand'],
  [/border-l-yellow-[0-9]+/g, 'border-l-medium'],
  
  // Print overrides to keep them readable (enterprise)
  [/print:text-slate-900/g, 'print:text-black'],
  [/print:text-slate-800/g, 'print:text-gray-900'],
  [/print:text-slate-700/g, 'print:text-gray-800'],
  [/print:text-slate-600/g, 'print:text-gray-600'],
  [/print:text-cyan-800/g, 'print:text-pqc'],
  [/print:text-amber-800/g, 'print:text-high'],
  [/print:text-amber-700/g, 'print:text-high'],
  [/print:text-rose-800/g, 'print:text-critical'],
  [/print:bg-slate-100/g, 'print:bg-white'],
  [/print:bg-amber-100/g, 'print:bg-white'],
  [/print:bg-rose-100/g, 'print:bg-white'],
  [/print:border-slate-300/g, 'print:border-gray-300'],
  [/print:border-amber-[0-9]+(\/[0-9]+)?/g, 'print:border-high'],
  [/print:bg-amber-50(\/[0-9]+)?/g, 'print:bg-white'],
  [/print:border-rose-[0-9]+/g, 'print:border-critical'],
];

const files = walkSync(path.join(__dirname, 'src'));

let changedCount = 0;
files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let newContent = content;
  
  mapRegex.forEach(([regex, replacement]) => {
    newContent = newContent.replace(regex, replacement);
  });
  
  // Clean up any double spaces generated by removing gradients
  newContent = newContent.replace(/  +/g, ' ');
  
  if (content !== newContent) {
    fs.writeFileSync(file, newContent, 'utf8');
    changedCount++;
  }
});

console.log(`Migrated final styling artifacts in ${changedCount} files.`);
